### ISSUE TITLE
有关 Vue cli splitechunk 问题。

### ISSUE THREAD

**Issue by StringKe** [MrGaoGang/mrgaogang#1]
[原文章](https://mrgaogang.github.io/vue/deep/Vue%E5%A4%9A%E5%85%A5%E5%8F%A3%E6%89%93%E5%8C%85%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96.html)

我使用了 ant-design-vue 这个ui组件，但是打包出来的文件内容里 只有对应的css js 文件依旧都打包到 chunk-common 中去了。

```
module.exports = {
  pages: {
    index: {
      chunks: [
        "chunk-vendors",
        "chunk-common",
        "app-common",
        "app-render",
        "antd",
        "index"
      ]
    },
    thumbnail: {
      chunks: [
        "chunk-vendors",
        "chunk-common",
        "app-common",
        "app-render",
        "thumbnail"
      ]
    }
  },
  configureWebpack: config => {
    config.optimization = {
      splitChunks: {
        cacheGroups: {
          // 抽离所有入口的公用资源为一个chunk
          common: {
            name: "chunk-common",
            chunks: "initial",
            minChunks: 2,
            maxInitialRequests: 5,
            minSize: 0,
            priority: 6,
            reuseExistingChunk: true,
            enforce: true
          },
          // 抽离node_modules下的库为一个chunk
          vendors: {
            name: "chunk-vendors",
            test: /[\\/]node_modules[\\/]/,
            chunks: "initial",
            priority: 2,
            reuseExistingChunk: true,
            enforce: true
          },
          antd: {
            name: "antd",
            test: /[\\/]node_modules[\\/](ant-design-vue|@ant-design)[\\/]/,
            chunks: "all",
            priority: 3,
            reuseExistingChunk: true,
            enforce: true
          },
          appRender: {
            name: "app-render",
            test: /[\\/]src[\\/]render[\\/]/,
            chunks: "all",
            priority: 5,
            reuseExistingChunk: true,
            enforce: true
          },
          appCommon: {
            name: "app-common",
            test: /[\\/]src[\\/]common[\\/]/,
            chunks: "all",
            priority: 4,
            reuseExistingChunk: true,
            enforce: true
          }
        }
      }
    };
  }
};
```

**Comment by MrGaoGang** [comment]
> [原文章](https://mrgaogang.github.io/vue/deep/Vue%E5%A4%9A%E5%85%A5%E5%8F%A3%E6%89%93%E5%8C%85%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96.html)
> 
> 我使用了 ant-design-vue 这个ui组件，但是打包出来的文件内容里 只有对应的css js 文件依旧都打包到 chunk-common 中去了。
> 
> ```
> module.exports = {
>   pages: {
>     index: {
>       chunks: [
>         "chunk-vendors",
>         "chunk-common",
>         "app-common",
>         "app-render",
>         "antd",
>         "index"
>       ]
>     },
>     thumbnail: {
>       chunks: [
>         "chunk-vendors",
>         "chunk-common",
>         "app-common",
>         "app-render",
>         "thumbnail"
>       ]
>     }
>   },
>   configureWebpack: config => {
>     config.optimization = {
>       splitChunks: {
>         cacheGroups: {
>           // 抽离所有入口的公用资源为一个chunk
>           common: {
>             name: "chunk-common",
>             chunks: "initial",
>             minChunks: 2,
>             maxInitialRequests: 5,
>             minSize: 0,
>             priority: 6,
>             reuseExistingChunk: true,
>             enforce: true
>           },
>           // 抽离node_modules下的库为一个chunk
>           vendors: {
>             name: "chunk-vendors",
>             test: /[\\/]node_modules[\\/]/,
>             chunks: "initial",
>             priority: 2,
>             reuseExistingChunk: true,
>             enforce: true
>           },
>           antd: {
>             name: "antd",
>             test: /[\\/]node_modules[\\/](ant-design-vue|@ant-design)[\\/]/,
>             chunks: "all",
>             priority: 3,
>             reuseExistingChunk: true,
>             enforce: true
>           },
>           appRender: {
>             name: "app-render",
>             test: /[\\/]src[\\/]render[\\/]/,
>             chunks: "all",
>             priority: 5,
>             reuseExistingChunk: true,
>             enforce: true
>           },
>           appCommon: {
>             name: "app-common",
>             test: /[\\/]src[\\/]common[\\/]/,
>             chunks: "all",
>             priority: 4,
>             reuseExistingChunk: true,
>             enforce: true
>           }
>         }
>       }
>     };
>   }
> };
> ```

hello , string; 抽离出公共js，

```js
common: {
            name: "chunk-common",
            chunks: "initial",
            minChunks: 2,
            maxInitialRequests: 5,
            minSize: 0,
            priority: 6,
            reuseExistingChunk: true,
            enforce: true
          },
```

此部分是依赖于多个入口的，我看你这边似乎没有配置多入口,你这边只配置了`thumbnail `和`index`但是未配置对应的entry和template导致无法解析。

**Comment by StringKe** [comment]
了解，我的原因是因为 分割页面后 逻辑功能js互相引用导致。分割之后大部分都在common中。
